---
services:

  postgres_cluster:
    container_name: postgres_cluster
    hostname: postgrescluster
    image: docker.io/library/postgres:16
    restart: unless-stopped
    volumes:
      - /mnt/data/appdata/postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    healthcheck:
      test: ["CMD", "pg_isready"]
      interval: 30s
      timeout: 20s
      retries: 3
    networks:
      - backend

networks:
  backend:
    external: true
